#! /bin/bash

dir=/home/arne/personal/dev/compiler/project/trunk

for i; do
echo "Compiling java sources"
if make --directory=$dir/java/; then
  echo "Compiling " $i
  if java -jar -ea $dir/java/bootstrap.jar $i
  then
    mkdir built
    mv $i.s built
    echo "Assembling:"
    if as built/$i.s -o built/$i.o;
    then
      echo "Linking: "
      if ld -dynamic-linker /lib/ld-linux.so.2 built/$i.o $dir/lib/libbarnex.o -lc -o built/$i.out;
      then
	echo "Running:"
	mv ./built/$i.out .;
	./$i.out;
      fi;
    fi;
  fi;
fi;
done;